-- SeaQuest Command Center — Supabase schema
-- Run this in Supabase → SQL Editor → New query → Run.

create table if not exists companies (
  id           bigint generated by default as identity primary key,
  name         text not null,
  industry     text,
  location     text,
  status       text,
  priority     boolean default false,
  phone_channel text,
  contact_name text,
  contact_title text,
  notes        text,
  created_at   timestamptz default now()
);

create table if not exists contacts (
  id          bigint generated by default as identity primary key,
  company_id  bigint references companies(id) on delete cascade,
  name        text,
  title       text,
  location    text,
  channel     text,
  status      text,
  notes       text,
  created_at  timestamptz default now()
);

create table if not exists quotes (
  id           bigint generated by default as identity primary key,
  company_id   bigint references companies(id) on delete set null,
  quote_number text,
  product      text,
  quantity     numeric,
  unit_price   numeric,
  total        numeric,
  status       text,
  notes        text,
  created_at   timestamptz default now()
);

-- Territories / TAM for the Global Domination game (optional; app also has defaults in config.js)
create table if not exists territories (
  id             bigint generated by default as identity primary key,
  name           text not null,
  kind           text,           -- 'Industry' | 'Global' | 'Geo'
  total_in_market bigint,
  notes          text
);

-- Row Level Security: any signed-in team member can read/write.
alter table companies   enable row level security;
alter table contacts    enable row level security;
alter table quotes      enable row level security;
alter table territories enable row level security;

create policy "team_all_companies"   on companies   for all to authenticated using (true) with check (true);
create policy "team_all_contacts"    on contacts    for all to authenticated using (true) with check (true);
create policy "team_all_quotes"      on quotes      for all to authenticated using (true) with check (true);
create policy "team_all_territories" on territories for all to authenticated using (true) with check (true);
